// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6rImOyMwm6CB20kioqb_lqB1ttCT_UE',
    appId: '1:1050542303430:web:56d204f0420238db908fc7',
    messagingSenderId: '1050542303430',
    projectId: 'acqs-e6fff',
    authDomain: 'acqs-e6fff.firebaseapp.com',
    storageBucket: 'acqs-e6fff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2oDyo773088E2K7jm-Ye8E7f5prJXtU',
    appId: '1:1050542303430:android:459c0c85787a6438908fc7',
    messagingSenderId: '1050542303430',
    projectId: 'acqs-e6fff',
    storageBucket: 'acqs-e6fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITCjJyFVLSsoQLcEo0NhuiP9xC3MyaKk',
    appId: '1:1050542303430:ios:5fd85d42ba125e5e908fc7',
    messagingSenderId: '1050542303430',
    projectId: 'acqs-e6fff',
    storageBucket: 'acqs-e6fff.appspot.com',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDITCjJyFVLSsoQLcEo0NhuiP9xC3MyaKk',
    appId: '1:1050542303430:ios:d25f94dd228d1e15908fc7',
    messagingSenderId: '1050542303430',
    projectId: 'acqs-e6fff',
    storageBucket: 'acqs-e6fff.appspot.com',
    iosBundleId: 'com.example.untitled6.RunnerTests',
  );
}
